apiVersion: v1
kind: Service
metadata:
  name: event-management-service
  namespace: event-management
  labels:
    app: event-management-app
spec:
  selector:
    app: event-management-app
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  type: ClusterIP 